Repository leits/MeetingBar, pull requests merged in 2024-06, with the labels that each got.

#730 Translations update from Hosted Weblate
  MeetingBar/Resources /Localization /sk.lproj/Localizable.strings
Labels: size:XS, lgtm

#735 Translations update from Hosted Weblate
  MeetingBar/Resources /Localization /pl.lproj/Localizable.strings
Labels: size:XS, lgtm

#731 Add support for zm.page links
  MeetingBar/Assets.xcassets/vendor-icons/zm_page_icon.imageset/Contents.json
  MeetingBar/Assets.xcassets/vendor-icons/zm_page_icon.imageset/zm_page_icon.svg
  MeetingBar/MeetingServices.swift
  MeetingBarTests/MeetingServicesTests.swift
  MeetingBarTests/Meetingbar-sample-data.ics
Labels: feature, size:M, lgtm

#732 Added support for Cal Video links
  MeetingBar/Assets.xcassets/vendor-icons/calcom_icon.imageset/Contents.json
  MeetingBar/Assets.xcassets/vendor-icons/calcom_icon.imageset/calcom_icon.png
  MeetingBar/MeetingServices.swift
  MeetingBarTests/MeetingServicesTests.swift
Labels: feature, size:S, lgtm

#738 Translations update from Hosted Weblate
  MeetingBar/Resources /Localization /hr.lproj/Localizable.strings
  MeetingBar/Resources /Localization /ko.lproj/Localizable.strings
  MeetingBar/Resources /Localization /pt-BR.lproj/Localizable.strings
Labels: size:S, lgtm

#740 Translations update from Hosted Weblate
  MeetingBar/Resources /Localization /de.lproj/Localizable.strings
Labels: size:S, lgtm

#741 Translations update from Hosted Weblate
  MeetingBar/Resources /Localization /es.lproj/Localizable.strings
Labels: size:XS, lgtm
