Repository leits/MeetingBar, pull requests merged in 2024-07, with the labels that each got.

#742 Translations update from Hosted Weblate
  MeetingBar/Resources /Localization /it.lproj/Localizable.strings
Labels: size:XS, lgtm

#746 Translations update from Hosted Weblate
  MeetingBar/Resources /Localization /sk.lproj/Localizable.strings
  MeetingBar/Resources /Localization /uk.lproj/Localizable.strings
Labels: size:M, lgtm

#750 Update pumble_icon.svg
  MeetingBar/Assets.xcassets/vendor-icons/pumble_icon.imageset/pumble_icon.svg
Labels: size:XS, lgtm

#748 added support for LiveKit Meet - https://meet.livekit.io/ - meeting links
  MeetingBar/Assets.xcassets/vendor-icons/livekit_icon.imageset/Contents.json
  MeetingBar/Assets.xcassets/vendor-icons/livekit_icon.imageset/livekit.png
  MeetingBar/MeetingServices.swift
  MeetingBarTests/MeetingServicesTests.swift
Labels: feature, size:S, lgtm
