Repository leits/MeetingBar, pull requests merged in 2024-12, with the labels that each got.

#786 Update Webex icon
  MeetingBar/Assets.xcassets/vendor-icons/webex_icon.imageset/webex_icon.png
Labels: size:XS, lgtm

#784 Update japanese translation for notifications
  MeetingBar/Resources /Localization /ja.lproj/Localizable.strings
Labels: size:S, lgtm

#780 Translations update from Hosted Weblate
  MeetingBar/Resources /Localization /es.lproj/Localizable.strings
  MeetingBar/Resources /Localization /pl.lproj/Localizable.strings
  MeetingBar/Resources /Localization /uk.lproj/Localizable.strings
Labels: size:S, lgtm

#783 Fix for xcode 16.1: using unsupported binding
  MeetingBar/Views/Shared.swift
Labels: bug, size:XS, lgtm
