Repository leits/MeetingBar, pull requests merged in 2025-05, with the labels that each got.

#815 Translations update from Hosted Weblate
  MeetingBar/Resources /Localization /fr.lproj/Localizable.strings
  MeetingBar/Resources /Localization /ja.lproj/Localizable.strings
  MeetingBar/Resources /Localization /ko.lproj/Localizable.strings
Labels: size:M

#810 Replace newlines with spaces in event title
  MeetingBar/StatusBarItemController.swift
Labels: size:XS, lgtm

#799 add Meetecho
  MeetingBar/Assets.xcassets/vendor-icons/meetecho_icon.imageset/Contents.json
  MeetingBar/Assets.xcassets/vendor-icons/meetecho_icon.imageset/meetecho.png
  MeetingBar/MeetingServices.swift
  MeetingBarTests/MeetingServicesTests.swift
Labels: feature, size:S, lgtm

#806 Feature: Add Calendar Information to AppleScript Interface
  MeetingBar/Scripts.swift
  MeetingBarTests/ScriptsTests.swift
Labels: feature, size:M, lgtm

#820 Translations update from Hosted Weblate
  MeetingBar/Resources /Localization /enm.lproj/Localizable.strings
  MeetingBar/Resources /Localization /he.lproj/Localizable.strings
  MeetingBar/Resources /Localization /uk.lproj/Localizable.strings
Labels: size:XS, lgtm

#821 Translations update from Hosted Weblate
  MeetingBar/Resources /Localization /es.lproj/Localizable.strings
  MeetingBar/Resources /Localization /it.lproj/Localizable.strings
  MeetingBar/Resources /Localization /pl.lproj/Localizable.strings
  MeetingBar/Resources /Localization /tr.lproj/Localizable.strings
  MeetingBar/Resources /Localization /uk.lproj/Localizable.strings
Labels: size:S, lgtm

#822 Translations update from Hosted Weblate
  MeetingBar/Resources /Localization /he.lproj/Localizable.strings
  MeetingBar/Resources /Localization /uk.lproj/Localizable.strings
Labels: size:S, lgtm

#823 fix: text key
  MeetingBar/UI/Views/Preferences/CalendarsTab.swift
Labels: bug, size:XS, lgtm

#819 Fix typo in translation files
  MeetingBar/Resources /Localization /cs.lproj/Localizable.strings
  MeetingBar/Resources /Localization /de.lproj/Localizable.strings
  MeetingBar/Resources /Localization /en.lproj/Localizable.strings
  MeetingBar/Resources /Localization /es.lproj/Localizable.strings
  MeetingBar/Resources /Localization /fr.lproj/Localizable.strings
  MeetingBar/Resources /Localization /he.lproj/Localizable.strings
  MeetingBar/Resources /Localization /hr.lproj/Localizable.strings
  MeetingBar/Resources /Localization /hu.lproj/Localizable.strings
  MeetingBar/Resources /Localization /it.lproj/Localizable.strings
  MeetingBar/Resources /Localization /ja.lproj/Localizable.strings
  MeetingBar/Resources /Localization /nb-NO.lproj/Localizable.strings
  MeetingBar/Resources /Localization /nl.lproj/Localizable.strings
  MeetingBar/Resources /Localization /pl.lproj/Localizable.strings
  MeetingBar/Resources /Localization /pt-BR.lproj/Localizable.strings
  MeetingBar/Resources /Localization /sk.lproj/Localizable.strings
  MeetingBar/Resources /Localization /ta.lproj/Localizable.strings
  MeetingBar/Resources /Localization /tr.lproj/Localizable.strings
  MeetingBar/Resources /Localization /uk.lproj/Localizable.strings
  MeetingBar/UI/Views/Preferences/BrowserConfigView.swift
Labels: size:L, lgtm

#824 Translations update from Hosted Weblate
  MeetingBar/Resources /Localization /uk.lproj/Localizable.strings
Labels: size:S, lgtm

#826 Translations update from Hosted Weblate
  MeetingBar/Resources /Localization /tr.lproj/Localizable.strings
  MeetingBar/Resources /Localization /uk.lproj/Localizable.strings
Labels: size:XS, lgtm

#818 Support non-app "browser" URLs
  MeetingBar/Extensions/URL.swift
Labels: feature, size:S, lgtm

#827 Translations update from Hosted Weblate
  MeetingBar/Resources /Localization /sk.lproj/Localizable.strings
Labels: size:S, lgtm
